[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/state"
  to = "/.netlify/functions/state"
  status = 200

[[redirects]]
  from = "/api/scan"
  to = "/.netlify/functions/scanner"
  status = 200

[functions]
  node_bundler = "esbuild"
